name: Backport reminder

on:
  pull_request_target:
    branches: [master]
    types: [closed]
  schedule:
    - cron: '0 6 * * *'  # Every day at 06:00 UTC
  workflow_dispatch:
    inputs:
      lookback_days:
        description: 'How many days back to search merged PRs'
        required: false
        default: '7'
      pending_label_age_days:
        description: 'Minimum age in days before reminding'
        required: false
        default: '14'

env:
    BACKPORT_TOKEN: ${{ secrets.BACKPORT_TOKEN }}

jobs:
  reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add Backport pending label (single PR)
        if: github.event_name == 'pull_request_target'
        run: |
          python github_ci_tools/scripts/backport.py label --pr-mode
          python github_ci_tools/scripts/backport.py remind --pr-mode --pending-reminder-age-days ${{ github.event.inputs.pending_label_age_days }}
      - name: Add Backport pending label (bulk)
        if: github.event_name != 'pull_request_target'
        run: |
          python github_ci_tools/scripts/backport.py label --lookback-days ${{ github.event.inputs.lookback_days }}
          python github_ci_tools/scripts/backport.py remind --lookback-days ${{ github.event.inputs.lookback_days }} --pending-reminder-age-days ${{ github.event.inputs.pending_label_age_days }}